### ISSUE TITLE
Import and Export Rainbow's replay buffer

### ISSUE THREAD

**Issue by mancoast** [unixpickle/anyrl-py#17]
Greetings!

Do you have any suggestions to transfer Rainbow's replay buffer with the model checkpoints?

Thanks,
coast

**Comment by unixpickle** [comment]
One naive thing you could do is just pickle the ReplayBuffer periodically.

The replay buffer can often be large (>10GiB), which means that you probably won't want to save it as often as the network weights. Also, it would be _really_ inefficient to store the entire replay buffer in the TF graph, which I believe you'd have to do to save it with tf.train.Saver.

**Comment by AurelianTactics** [comment]
I did the naive interpretation of this in PrioritizedReplayBuffer in replay.py. A 500,000 capacity replay buffer saved to 4.6 GB. I've been using the functions below in the dqn.py train function.

```
    #saving replay buffer to pickle file
    def save_samples(self):
        with open('transitions.p','wb') as handle:
            pickle.dump(self.transitions,handle,protocol=pickle.HIGHEST_PROTOCOL)

    #loading replay buffer from pickle file
        #have to add sample by sample due to populating the errors into the FloatBuffer (self.errors)
    def load_samples(self):
        temp_trans = pickle.load(open("transitions.p","rb"))
        for i in temp_trans:
            self.add_sample(i)
        print("loaded transitions: ",len(self.transitions))
```
